import { describe, expect, it } from "@effect/vitest";
import { Effect } from "effect";
import { buildJsonSchema } from "../../scripts/codegen/buildJsonSchema";
import { postProcessAst } from "../../scripts/codegen/postProcessAst";
import { renderSchemaSource } from "../../scripts/codegen/renderSchemaSource";
import type { ClassTable } from "../../scripts/codegen/parseTtl";

describe("renderSchemaSource", () => {
  it.effect("emits header + branded IRI const + Schema.Class for a class", () =>
    Effect.gen(function* () {
      const table: ClassTable = {
        classes: [
          {
            iri: "https://w3id.org/energy-intel/Expert",
            label: "Expert",
            definition: "An energy expert.",
            superClasses: [],
            disjointWith: [],
            equivalentClassRestrictions: [],
            properties: []
          }
        ],
        prefixes: {}
      };
      const jsonSchema = buildJsonSchema(table);
      const processed = yield* postProcessAst(jsonSchema, table);
      const source = renderSchemaSource(processed, table);

      expect(source).toContain("// Generated by");
      expect(source).toContain('import { Schema } from "effect";');
      expect(source).toContain("export const ExpertIri = Schema.String.pipe(");
      expect(source).toContain("Schema.check(Schema.isPattern(");
      expect(source).toContain('Schema.brand("ExpertIri")');
      expect(source).toContain(
        "export type ExpertIri = typeof ExpertIri.Type;"
      );
      expect(source).toContain(
        'export class Expert extends Schema.Class<Expert>("Expert")({'
      );
      expect(source).toContain("iri: ExpertIri");
      // The skos:definition surfaces as a doc-comment line.
      expect(source).toContain("An energy expert.");
    })
  );

  it.effect("escapes forward slashes in branded IRI regex literal", () =>
    Effect.gen(function* () {
      const table: ClassTable = {
        classes: [
          {
            iri: "https://w3id.org/energy-intel/Expert",
            label: "Expert",
            superClasses: [],
            disjointWith: [],
            equivalentClassRestrictions: [],
            properties: []
          }
        ],
        prefixes: {}
      };
      const jsonSchema = buildJsonSchema(table);
      const processed = yield* postProcessAst(jsonSchema, table);
      const source = renderSchemaSource(processed, table);

      // Regex literal must not contain a bare `/` inside the body that
      // would terminate the literal early.
      expect(source).toContain(
        "Schema.isPattern(/^https:\\/\\/w3id\\.org\\/energy-intel\\/expert\\/[A-Za-z0-9_-]+$/)"
      );
    })
  );

  it.effect("emits dependents after dependencies (topological order)", () =>
    Effect.gen(function* () {
      const table: ClassTable = {
        classes: [
          {
            iri: "https://w3id.org/energy-intel/Expert",
            label: "Expert",
            superClasses: [],
            disjointWith: [],
            equivalentClassRestrictions: [],
            properties: [
              {
                iri: "http://purl.obolibrary.org/obo/BFO_0000053",
                range: "https://w3id.org/energy-intel/EnergyExpertRole",
                optional: true,
                list: false
              }
            ]
          },
          {
            iri: "https://w3id.org/energy-intel/EnergyExpertRole",
            label: "EnergyExpertRole",
            superClasses: [],
            disjointWith: [],
            equivalentClassRestrictions: [],
            properties: []
          }
        ],
        prefixes: {}
      };
      const jsonSchema = buildJsonSchema(table);
      const processed = yield* postProcessAst(jsonSchema, table);
      const source = renderSchemaSource(processed, table);

      // EnergyExpertRole class must be declared before Expert (which
      // references its branded IRI).
      const roleClassIdx = source.indexOf("class EnergyExpertRole extends");
      const expertClassIdx = source.indexOf("class Expert extends");
      expect(roleClassIdx).toBeGreaterThanOrEqual(0);
      expect(expertClassIdx).toBeGreaterThanOrEqual(0);
      expect(roleClassIdx).toBeLessThan(expertClassIdx);
      // And the cross-class property is wired to the target brand.
      expect(source).toContain(
        "BFO_0000053: Schema.optional(EnergyExpertRoleIri)"
      );
    })
  );

  it.effect("renders xsd primitive properties as Schema.String / Schema.Number", () =>
    Effect.gen(function* () {
      const table: ClassTable = {
        classes: [
          {
            iri: "https://w3id.org/energy-intel/Expert",
            label: "Expert",
            superClasses: [],
            disjointWith: [],
            equivalentClassRestrictions: [],
            properties: [
              {
                iri: "http://xmlns.com/foaf/0.1/name",
                range: "http://www.w3.org/2001/XMLSchema#string",
                optional: true,
                list: false
              },
              {
                iri: "https://w3id.org/energy-intel/age",
                range: "http://www.w3.org/2001/XMLSchema#integer",
                optional: true,
                list: false
              }
            ]
          }
        ],
        prefixes: {}
      };
      const jsonSchema = buildJsonSchema(table);
      const processed = yield* postProcessAst(jsonSchema, table);
      const source = renderSchemaSource(processed, table);

      expect(source).toContain("name: Schema.optional(Schema.String)");
      expect(source).toContain("age: Schema.optional(Schema.Number)");
    })
  );

  it.effect("includes equivalentClass restrictions in the doc comment", () =>
    Effect.gen(function* () {
      const table: ClassTable = {
        classes: [
          {
            iri: "https://w3id.org/energy-intel/Expert",
            label: "Expert",
            superClasses: [],
            disjointWith: [],
            equivalentClassRestrictions: [
              {
                onProperty: "http://purl.obolibrary.org/obo/BFO_0000053",
                someValuesFrom: "https://w3id.org/energy-intel/EnergyExpertRole"
              }
            ],
            properties: []
          },
          {
            iri: "https://w3id.org/energy-intel/EnergyExpertRole",
            label: "EnergyExpertRole",
            superClasses: [],
            disjointWith: [],
            equivalentClassRestrictions: [],
            properties: []
          }
        ],
        prefixes: {}
      };
      const jsonSchema = buildJsonSchema(table);
      const processed = yield* postProcessAst(jsonSchema, table);
      const source = renderSchemaSource(processed, table);

      // The owl:equivalentClass restriction surfaces as a JSDoc line above
      // the Schema.Class.
      expect(source).toContain("Expert ≡ ∃BFO_0000053.EnergyExpertRole");
    })
  );
});
