/**
 * Emit generated TypeScript constants for ontology_skill SKOS concepts.
 */
import type { ConceptSchemeTable } from "./parseConceptSchemes.ts";

const GENERATED_NOTICE = `// Generated by packages/ontology-store/scripts/generate-concepts-from-ttl.ts.
// Do not edit by hand.`;

const stringify = (value: unknown): string => JSON.stringify(value, null, 2);

export const emitConceptSchemeModule = (table: ConceptSchemeTable): string =>
  [
    GENERATED_NOTICE,
    "",
    `export const ENERGY_INTEL_CONCEPT_SCHEMES = ${stringify(table.schemes)} as const;`,
    "",
    `export type EnergyIntelConceptScheme = (typeof ENERGY_INTEL_CONCEPT_SCHEMES)[number];`,
    "",
    `export const ENERGY_INTEL_CONCEPTS = ${stringify(table.concepts)} as const;`,
    "",
    `export type EnergyIntelConcept = (typeof ENERGY_INTEL_CONCEPTS)[number];`,
    "",
    `export const ENERGY_INTEL_CONCEPTS_BY_IRI = Object.fromEntries(`,
    `  ENERGY_INTEL_CONCEPTS.map((concept) => [concept.iri, concept])`,
    `) as Readonly<Record<string, EnergyIntelConcept>>;`,
    ""
  ].join("\n");
