/**
 * Stage 5 of the TTL → Effect Schema codegen pipeline: take the
 * `ProcessedAst` (Task 8) plus the original `ClassTable` (Task 6) and
 * render an idiomatic Effect Schema TS source file ready to be written
 * to `packages/ontology-store/src/generated/<module>.ts`.
 *
 * Approach: hand-rolled string emitter (the Approach A from the slice
 * impl plan). The `MultiDocument` we computed in Task 8 is preserved for
 * future reasoner extensions, but for now we drive emission directly off
 * `processed.emitOrder` + `processed.brandedIris` + `table.classes`.
 * `SchemaRepresentation.toCodeDocument` is the preferred Effect-native
 * codegen surface for plain schema bodies, and this pipeline already builds
 * the `MultiDocument` in `postProcessAst`. The final emission still keeps a
 * small custom wrapper because the ontology contract needs generated
 * `Schema.Class` exports, branded IRI fields, subclass-IRI widening, and
 * class doc comments. Do not extend this file into runtime registry or
 * provisioning generation; those should be generated from a dedicated typed
 * manifest or from Effect's code document output.
 *
 * Output shape per class:
 *
 *   export const ExpertIri = Schema.String.pipe(
 *     Schema.check(Schema.isPattern(/^https:\/\/.../)),
 *     Schema.brand("ExpertIri"),
 *   )
 *   export type ExpertIri = typeof ExpertIri.Type
 *
 *   /**
 *    * Expert
 *    *
 *    * <skos:definition>
 *    *
 *    * Expert ≡ ∃BFO_0000053.EnergyExpertRole
 *    *\/
 *   export class Expert extends Schema.Class<Expert>("Expert")({
 *     iri: ExpertIri,
 *     <propKey>: <propType>,
 *     ...
 *   }) {}
 *
 * Cross-class property ranges are wired to the target class's brand
 * (e.g. `ei:bearerOf -> EnergyExpertRoleIri`). XSD primitives use the
 * native `Schema.String / Schema.Number / Schema.Boolean`. Optional
 * properties are wrapped in `Schema.optional(...)`. List properties are
 * wrapped in `Schema.Array(...)` (and may compose with `Schema.optional`).
 *
 * Determinism / idempotence: emit order is fixed by `processed.emitOrder`,
 * properties iterate in their `ClassTable` order, the header is fixed,
 * and there are no Date / random / env reads. Re-running this against
 * the same input yields byte-identical output — the drift gate test
 * (Task 9) depends on this.
 */
import type { ClassProperty, ClassRecord, ClassTable } from "./parseTtl.ts";
import type {
  BrandedIriMetadata,
  ProcessedAst
} from "./postProcessAst.ts";

/**
 * XSD datatype IRI → Effect Schema primitive expression. Mirrors
 * `XSD_TYPE_MAP` in `buildJsonSchema.ts` so the codegen pipeline can't
 * disagree with itself about how to lower a TTL range.
 */
const XSD_TO_SCHEMA: Readonly<Record<string, string>> = {
  "http://www.w3.org/2001/XMLSchema#string": "Schema.String",
  "http://www.w3.org/2001/XMLSchema#integer": "Schema.Number",
  "http://www.w3.org/2001/XMLSchema#decimal": "Schema.Number",
  "http://www.w3.org/2001/XMLSchema#double": "Schema.Number",
  "http://www.w3.org/2001/XMLSchema#float": "Schema.Number",
  "http://www.w3.org/2001/XMLSchema#boolean": "Schema.Boolean",
  // ISO-8601 datetimes/dates ride as strings for now; consumers can
  // refine via Schema.transform when the need arises.
  "http://www.w3.org/2001/XMLSchema#dateTime": "Schema.String",
  "http://www.w3.org/2001/XMLSchema#date": "Schema.String"
};

const GENERATED_NOTICE = `// Generated by packages/ontology-store/scripts/generate-from-ttl.ts.
// Do not edit by hand.`;

const HEADER = `${GENERATED_NOTICE}

import { Schema } from "effect";

`;

/**
 * Last URL path segment / fragment, sanitised to identifier-safe chars.
 * Mirrors the helper in `buildJsonSchema.ts` / `postProcessAst.ts` so a
 * property's emitted key matches the JSON Schema property key 1:1.
 */
const propLocalName = (iri: string): string => {
  const hashIdx = iri.lastIndexOf("#");
  const tail =
    hashIdx >= 0 ? iri.slice(hashIdx + 1) : iri.slice(iri.lastIndexOf("/") + 1);
  const sanitized = tail.replace(/[^A-Za-z0-9_]+/g, "_");
  return sanitized.length === 0 ? "_" : sanitized;
};

/**
 * Build a child lookup so a property whose ontology range is an abstract local
 * class accepts the branded IRIs for concrete local subclasses too. Example:
 * `Post.presents` ranges over `MediaAttachment`, so generated TS accepts
 * `MediaAttachmentIri | ChartIri | ScreenshotIri | ...`.
 */
const descendantIrisByClass = (
  table: ClassTable
): ReadonlyMap<string, ReadonlyArray<string>> => {
  const childrenByParent = new Map<string, Array<string>>();
  for (const cls of table.classes) {
    for (const parent of cls.superClasses) {
      const children = childrenByParent.get(parent) ?? [];
      children.push(cls.iri);
      childrenByParent.set(parent, children);
    }
  }

  const collect = (iri: string, seen: Set<string>): ReadonlyArray<string> => {
    const out: Array<string> = [];
    for (const child of childrenByParent.get(iri) ?? []) {
      if (seen.has(child)) continue;
      seen.add(child);
      out.push(child, ...collect(child, seen));
    }
    return out;
  };

  return new Map(table.classes.map((cls) => [cls.iri, collect(cls.iri, new Set())]));
};

const renderRangeType = (
  range: string | undefined,
  brandsByIri: ReadonlyMap<string, BrandedIriMetadata>,
  descendantIrisByIri: ReadonlyMap<string, ReadonlyArray<string>>
): string => {
  if (range === undefined) {
    return "Schema.String";
  }
  const xsd = XSD_TO_SCHEMA[range];
  if (xsd !== undefined) {
    return xsd;
  }
  const targetBrand = brandsByIri.get(range);
  if (targetBrand === undefined) return "Schema.String";

  const brands = [
    targetBrand,
    ...(descendantIrisByIri.get(range) ?? [])
      .map((iri) => brandsByIri.get(iri))
      .filter((brand): brand is BrandedIriMetadata => brand !== undefined)
  ];
  const brandNames = [...new Set(brands.map((brand) => brand.brandName))];
  return brandNames.length === 1
    ? brandNames[0]!
    : `Schema.Union([${brandNames.join(", ")}])`;
};

const renderPropertyType = (
  prop: ClassProperty,
  brandsByIri: ReadonlyMap<string, BrandedIriMetadata>,
  descendantIrisByIri: ReadonlyMap<string, ReadonlyArray<string>>
): string => {
  const rangeUnion = prop.rangeUnion;
  const base =
    rangeUnion === undefined
      ? renderRangeType(prop.range, brandsByIri, descendantIrisByIri)
      : rangeUnion.length === 1
        ? renderRangeType(rangeUnion[0], brandsByIri, descendantIrisByIri)
        : `Schema.Union([${rangeUnion
            .map((range) =>
              renderRangeType(range, brandsByIri, descendantIrisByIri)
            )
            .join(", ")}])`;
  return prop.list ? `Schema.Array(${base})` : base;
};

/**
 * Render the doc-comment lines for a class. Captures the rdfs:label,
 * skos:definition (when present), and any owl:equivalentClass restriction
 * docs surfaced by `postProcessAst`. Returns the lines including the
 * leading `/**` / trailing `*\/` markers; an empty array means no doc
 * should be emitted (rare — every TTL class has at least a label).
 */
const renderDocComment = (
  cls: ClassRecord,
  brand: BrandedIriMetadata
): ReadonlyArray<string> => {
  const lines: Array<string> = [];
  lines.push(`/**`);
  lines.push(` * ${cls.label}`);
  if (cls.definition !== undefined && cls.definition.length > 0) {
    lines.push(` *`);
    lines.push(` * ${cls.definition}`);
  }
  for (const doc of brand.equivalentClassDoc) {
    lines.push(` *`);
    lines.push(` * ${doc}`);
  }
  lines.push(` */`);
  return lines;
};

/**
 * Escape any unescaped `/` in a regex source string so it can be safely
 * embedded inside a JS regex literal `/<pattern>/`. Backslashes preceding
 * the slash mean it's already escaped (e.g. `\.`); leave those alone.
 *
 * `postProcessAst.iriPatternForClass` returns patterns like
 * `^https://w3id\.org/energy-intel/expert/[A-Za-z0-9_-]+$` — every `/` in
 * the body would terminate the literal early, so we double-escape them
 * before emission.
 */
const escapeRegexSlashes = (pattern: string): string =>
  pattern.replace(/(?<!\\)\//g, "\\/");

const renderBrandedIri = (brand: BrandedIriMetadata): ReadonlyArray<string> => [
  `export const ${brand.brandName} = Schema.String.pipe(`,
  `  Schema.check(Schema.isPattern(/${escapeRegexSlashes(brand.pattern)}/)),`,
  `  Schema.brand("${brand.brandName}")`,
  `);`,
  `export type ${brand.brandName} = typeof ${brand.brandName}.Type;`,
  ``
];

const renderClassDef = (
  cls: ClassRecord,
  brand: BrandedIriMetadata,
  brandsByIri: ReadonlyMap<string, BrandedIriMetadata>,
  descendantIrisByIri: ReadonlyMap<string, ReadonlyArray<string>>
): ReadonlyArray<string> => {
  const lines: Array<string> = [];
  lines.push(...renderDocComment(cls, brand));
  lines.push(
    `export class ${brand.className} extends Schema.Class<${brand.className}>("${brand.className}")({`
  );
  lines.push(`  iri: ${brand.brandName}${cls.properties.length > 0 ? "," : ""}`);
  for (let i = 0; i < cls.properties.length; i++) {
    const prop = cls.properties[i]!;
    const key = propLocalName(prop.iri);
    const propType = renderPropertyType(prop, brandsByIri, descendantIrisByIri);
    const wrapped = prop.optional ? `Schema.optional(${propType})` : propType;
    const isLast = i === cls.properties.length - 1;
    lines.push(`  ${key}: ${wrapped}${isLast ? "" : ","}`);
  }
  lines.push(`}) {}`);
  lines.push(``);
  return lines;
};

export const renderSchemaSource = (
  processed: ProcessedAst,
  table: ClassTable
): string => {
  if (processed.emitOrder.length === 0) return `${GENERATED_NOTICE}\n`;

  const classByIri = new Map(table.classes.map((c) => [c.iri, c]));
  const brandsByIri = new Map(
    processed.brandedIris.map((b) => [b.classIri, b])
  );
  const descendantIrisByIri = descendantIrisByClass(table);
  const lines: Array<string> = [HEADER.trimEnd(), ""];

  // Emit branded IRI consts first so subsequent class definitions can
  // reference them without forward-decl issues. Use the same topological
  // emit order as the classes themselves — it doesn't matter for brand
  // consts (they're independent), but it keeps the file deterministic.
  for (const iri of processed.emitOrder) {
    const brand = brandsByIri.get(iri);
    if (brand === undefined) continue;
    lines.push(...renderBrandedIri(brand));
  }

  // Emit Schema.Class definitions in topological order.
  for (const iri of processed.emitOrder) {
    const cls = classByIri.get(iri);
    const brand = brandsByIri.get(iri);
    if (cls === undefined || brand === undefined) continue;
    lines.push(...renderClassDef(cls, brand, brandsByIri, descendantIrisByIri));
  }

  return lines.join("\n");
};
