// Generated by packages/ontology-store/scripts/generate-from-ttl.ts.
// Do not edit by hand.

import { DataFactory } from "n3";

const { namedNode } = DataFactory;

export const EI = {
  DataProviderRole: namedNode("https://w3id.org/energy-intel/DataProviderRole"),
  EnergyExpertRole: namedNode("https://w3id.org/energy-intel/EnergyExpertRole"),
  Expert: namedNode("https://w3id.org/energy-intel/Expert"),
  Organization: namedNode("https://w3id.org/energy-intel/Organization"),
  PublisherRole: namedNode("https://w3id.org/energy-intel/PublisherRole"),
} as const;

export const BFO = {

} as const;

export const FOAF = {
  Organization: namedNode("http://xmlns.com/foaf/0.1/Organization"),
  Person: namedNode("http://xmlns.com/foaf/0.1/Person"),
  name: namedNode("http://xmlns.com/foaf/0.1/name"),
} as const;

export const RDF = {
  first: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#first"),
  nil: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"),
  rest: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#rest"),
  type: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"),
} as const;

export const RDFS = {
  label: namedNode("http://www.w3.org/2000/01/rdf-schema#label"),
  subClassOf: namedNode("http://www.w3.org/2000/01/rdf-schema#subClassOf"),
} as const;

export const OWL = {
  Class: namedNode("http://www.w3.org/2002/07/owl#Class"),
  Restriction: namedNode("http://www.w3.org/2002/07/owl#Restriction"),
} as const;

export const SKOS = {
  definition: namedNode("http://www.w3.org/2004/02/skos/core#definition"),
} as const;

export const XSD = {
  dateTime: namedNode("http://www.w3.org/2001/XMLSchema#dateTime"),
  integer: namedNode("http://www.w3.org/2001/XMLSchema#integer"),
  string: namedNode("http://www.w3.org/2001/XMLSchema#string"),
} as const;
