// Generated by packages/ontology-store/scripts/generate-from-ttl.ts.
// Do not edit by hand.

import { DataFactory } from "n3";

const { namedNode } = DataFactory;

export const EI = {
  CanonicalMeasurementClaim: namedNode("https://w3id.org/energy-intel/CanonicalMeasurementClaim"),
  Chart: namedNode("https://w3id.org/energy-intel/Chart"),
  ClaimTemporalWindow: namedNode("https://w3id.org/energy-intel/ClaimTemporalWindow"),
  Conversation: namedNode("https://w3id.org/energy-intel/Conversation"),
  DataProviderRole: namedNode("https://w3id.org/energy-intel/DataProviderRole"),
  EnergyExpertRole: namedNode("https://w3id.org/energy-intel/EnergyExpertRole"),
  EvidenceSource: namedNode("https://w3id.org/energy-intel/EvidenceSource"),
  Excerpt: namedNode("https://w3id.org/energy-intel/Excerpt"),
  Expert: namedNode("https://w3id.org/energy-intel/Expert"),
  GenericImageAttachment: namedNode("https://w3id.org/energy-intel/GenericImageAttachment"),
  MediaAttachment: namedNode("https://w3id.org/energy-intel/MediaAttachment"),
  Observation: namedNode("https://w3id.org/energy-intel/Observation"),
  Organization: namedNode("https://w3id.org/energy-intel/Organization"),
  PodcastEpisode: namedNode("https://w3id.org/energy-intel/PodcastEpisode"),
  PodcastSegment: namedNode("https://w3id.org/energy-intel/PodcastSegment"),
  Post: namedNode("https://w3id.org/energy-intel/Post"),
  PublisherRole: namedNode("https://w3id.org/energy-intel/PublisherRole"),
  Screenshot: namedNode("https://w3id.org/energy-intel/Screenshot"),
  Series: namedNode("https://w3id.org/energy-intel/Series"),
  SocialThread: namedNode("https://w3id.org/energy-intel/SocialThread"),
  Variable: namedNode("https://w3id.org/energy-intel/Variable"),
  aboutTechnology: namedNode("https://w3id.org/energy-intel/aboutTechnology"),
  affiliatedWith: namedNode("https://w3id.org/energy-intel/affiliatedWith"),
  assertedTime: namedNode("https://w3id.org/energy-intel/assertedTime"),
  assertedUnit: namedNode("https://w3id.org/energy-intel/assertedUnit"),
  assertedValue: namedNode("https://w3id.org/energy-intel/assertedValue"),
  authoredBy: namedNode("https://w3id.org/energy-intel/authoredBy"),
  canonicalUnit: namedNode("https://w3id.org/energy-intel/canonicalUnit"),
  evidences: namedNode("https://w3id.org/energy-intel/evidences"),
  excerptFrom: namedNode("https://w3id.org/energy-intel/excerptFrom"),
  hasSegmentIndex: namedNode("https://w3id.org/energy-intel/hasSegmentIndex"),
  hasSeries: namedNode("https://w3id.org/energy-intel/hasSeries"),
  implementsVariable: namedNode("https://w3id.org/energy-intel/implementsVariable"),
  inConversation: namedNode("https://w3id.org/energy-intel/inConversation"),
  intervalEnd: namedNode("https://w3id.org/energy-intel/intervalEnd"),
  intervalStart: namedNode("https://w3id.org/energy-intel/intervalStart"),
  mentions: namedNode("https://w3id.org/energy-intel/mentions"),
  partOfEpisode: namedNode("https://w3id.org/energy-intel/partOfEpisode"),
  presents: namedNode("https://w3id.org/energy-intel/presents"),
  publishedInDataset: namedNode("https://w3id.org/energy-intel/publishedInDataset"),
  rawDims: namedNode("https://w3id.org/energy-intel/rawDims"),
  rawLabel: namedNode("https://w3id.org/energy-intel/rawLabel"),
  references: namedNode("https://w3id.org/energy-intel/references"),
  referencesAgent: namedNode("https://w3id.org/energy-intel/referencesAgent"),
  referencesDataset: namedNode("https://w3id.org/energy-intel/referencesDataset"),
  referencesDistribution: namedNode("https://w3id.org/energy-intel/referencesDistribution"),
  referencesSeries: namedNode("https://w3id.org/energy-intel/referencesSeries"),
  referencesVariable: namedNode("https://w3id.org/energy-intel/referencesVariable"),
  repliesTo: namedNode("https://w3id.org/energy-intel/repliesTo"),
  screenshotOf: namedNode("https://w3id.org/energy-intel/screenshotOf"),
  spokenBy: namedNode("https://w3id.org/energy-intel/spokenBy"),
} as const;

export const BFO = {
  bearerOf: namedNode("http://purl.obolibrary.org/obo/BFO_0000053"),
  inheresIn: namedNode("http://purl.obolibrary.org/obo/BFO_0000052"),
} as const;

export const FOAF = {
  Organization: namedNode("http://xmlns.com/foaf/0.1/Organization"),
  Person: namedNode("http://xmlns.com/foaf/0.1/Person"),
  name: namedNode("http://xmlns.com/foaf/0.1/name"),
} as const;

export const RDF = {
  first: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#first"),
  nil: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"),
  rest: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#rest"),
  type: namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"),
} as const;

export const RDFS = {
  label: namedNode("http://www.w3.org/2000/01/rdf-schema#label"),
  subClassOf: namedNode("http://www.w3.org/2000/01/rdf-schema#subClassOf"),
} as const;

export const OWL = {
  Class: namedNode("http://www.w3.org/2002/07/owl#Class"),
  Restriction: namedNode("http://www.w3.org/2002/07/owl#Restriction"),
} as const;

export const SKOS = {
  definition: namedNode("http://www.w3.org/2004/02/skos/core#definition"),
} as const;

export const XSD = {
  dateTime: namedNode("http://www.w3.org/2001/XMLSchema#dateTime"),
  integer: namedNode("http://www.w3.org/2001/XMLSchema#integer"),
  string: namedNode("http://www.w3.org/2001/XMLSchema#string"),
} as const;
