import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type WorkerSpec = {
  readonly label: "Ingest" | "Agent";
  readonly configs: ReadonlyArray<string>;
  readonly envInterface: string;
};

const workerSpecs: ReadonlyArray<WorkerSpec> = [
  {
    label: "Ingest",
    configs: ["wrangler.toml"],
    envInterface: "CloudflareIngestEnv"
  },
  {
    label: "Agent",
    configs: ["wrangler.agent.toml", "wrangler.toml"],
    envInterface: "CloudflareAgentEnv"
  }
];

const combinedOutputPath = "worker-configuration.d.ts";
const runtimeOutputPath = "worker-runtime.d.ts";
const projectRoot = import.meta.dir + "/..";
const propertyLinePattern = /^(\s*)([A-Z0-9_]+)(\??:\s.*)$/;

const run = (cmd: ReadonlyArray<string>) => {
  const result = Bun.spawnSync({
    cmd: [...cmd],
    cwd: projectRoot,
    stdout: "inherit",
    stderr: "inherit"
  });

  if (result.exitCode !== 0) {
    process.exit(result.exitCode);
  }
};

const extractInterfaceBody = (
  source: string,
  interfaceName: string
): ReadonlyArray<string> => {
  const lines = source.split("\n");
  const start = lines.findIndex((line) => line.trim() === `interface ${interfaceName} {`);

  if (start < 0) {
    throw new Error(`Could not find interface ${interfaceName}`);
  }

  const body: Array<string> = [];

  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];

    if (line.trim() === "}") {
      return body;
    }

    body.push(line);
  }

  throw new Error(`Could not find closing brace for interface ${interfaceName}`);
};

const normalizeGeneratedImports = (source: string) =>
  source.replaceAll('import("../../src/', 'import("./src/');

const normalizeGeneratedWhitespace = (source: string) =>
  source
    .replace(/^ +\t/gm, "\t")
    .replace(/[ \t]+$/gm, "");

const extractAllowedKeys = (configPath: string): ReadonlySet<string> => {
  const source = readFileSync(join(projectRoot, configPath), "utf8");
  const keys = new Set<string>();

  for (const match of source.matchAll(/binding\s*=\s*"([A-Z0-9_]+)"/g)) {
    keys.add(match[1]);
  }

  for (
    const match of source.matchAll(
      /\[\[[^\]]*durable_objects\.bindings\]\][\s\S]*?name\s*=\s*"([A-Z0-9_]+)"/g
    )
  ) {
    keys.add(match[1]);
  }

  let inVarsBlock = false;

  for (const rawLine of source.split("\n")) {
    const line = rawLine.trim();

    if (line.startsWith("[") && line.endsWith("]")) {
      inVarsBlock = line === "[vars]" || line === "[env.staging.vars]";
      continue;
    }

    if (!inVarsBlock) {
      continue;
    }

    const match = line.match(/^([A-Z0-9_]+)\s*=/);

    if (match) {
      keys.add(match[1]);
    }
  }

  return keys;
};

const filterInterfaceBody = (
  lines: ReadonlyArray<string>,
  allowedKeys: ReadonlySet<string>
) =>
  lines.filter((line) => {
    const match = line.match(propertyLinePattern);
    return match == null || allowedKeys.has(match[2]);
  });

const formatInterfaceBody = (lines: ReadonlyArray<string>) =>
  normalizeGeneratedImports(
    lines.map((line) => `  ${line.replace(/^\t/, "")}`).join("\n")
  );

mkdirSync(join(projectRoot, ".cache"), { recursive: true });
const tempDir = mkdtempSync(join(projectRoot, ".cache", "wrangler-types-"));

try {
  const generatedSections = workerSpecs.map((spec) => {
    const rawPath = join(tempDir, `${spec.label.toLowerCase()}.d.ts`);
    const allowedKeys = extractAllowedKeys(spec.configs[0]!);

    run([
      "bunx",
      "wrangler",
      "types",
      ...spec.configs.flatMap((config) => ["--config", config]),
      "--env-interface",
      spec.envInterface,
      rawPath
    ]);

    const raw = readFileSync(rawPath, "utf8");

    return {
      label: spec.label,
      env: formatInterfaceBody(
        filterInterfaceBody(extractInterfaceBody(raw, "Env"), allowedKeys)
      ),
      stagingEnv: formatInterfaceBody(
        filterInterfaceBody(extractInterfaceBody(raw, "StagingEnv"), allowedKeys)
      )
    };
  });

  const runtimeRawPath = join(tempDir, "runtime.d.ts");
  run([
    "bunx",
    "wrangler",
    "types",
    "--config",
    "wrangler.toml",
    "--include-env",
    "false",
    runtimeRawPath
  ]);
  writeFileSync(
    runtimeOutputPath,
    normalizeGeneratedWhitespace(
      normalizeGeneratedImports(readFileSync(runtimeRawPath, "utf8"))
    )
  );

  const combinedOutput = [
    "/* eslint-disable */",
    "// Generated by `bun run cf:types`. Do not edit by hand.",
    `/// <reference path="./${runtimeOutputPath}" />`,
    "declare namespace WorkerConfiguration {",
    ...generatedSections.flatMap((section) => [
      `  interface ${section.label}StagingEnv {`,
      section.stagingEnv,
      "  }",
      "",
      `  interface ${section.label}Env {`,
      section.env,
      "  }",
      ""
    ]),
    "}"
  ].join("\n");

  writeFileSync(combinedOutputPath, normalizeGeneratedWhitespace(combinedOutput));
} finally {
  rmSync(tempDir, { recursive: true, force: true });
}
