import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type WorkerSpec = {
  readonly label: "Ingest" | "Agent" | "Resolver";
  readonly config: string;
  readonly envInterface: string;
};

const workerSpecs: ReadonlyArray<WorkerSpec> = [
  {
    label: "Ingest",
    config: "wrangler.toml",
    envInterface: "CloudflareIngestEnv"
  },
  {
    label: "Agent",
    config: "wrangler.agent.toml",
    envInterface: "CloudflareAgentEnv"
  },
  {
    label: "Resolver",
    config: "wrangler.resolver.toml",
    envInterface: "CloudflareResolverEnv"
  }
];

const combinedOutputPath = "worker-configuration.d.ts";
const runtimeOutputPath = "worker-runtime.d.ts";
const projectRoot = import.meta.dir + "/..";

const run = (cmd: ReadonlyArray<string>) => {
  const result = Bun.spawnSync({
    cmd: [...cmd],
    cwd: projectRoot,
    stdout: "inherit",
    stderr: "inherit"
  });

  if (result.exitCode !== 0) {
    process.exit(result.exitCode);
  }
};

const extractInterfaceBody = (
  source: string,
  interfaceName: string
): ReadonlyArray<string> => {
  const lines = source.split("\n");
  const start = lines.findIndex((line) => line.trim() === `interface ${interfaceName} {`);

  if (start < 0) {
    throw new Error(`Could not find interface ${interfaceName}`);
  }

  const body: Array<string> = [];

  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];

    if (line.trim() === "}") {
      return body;
    }

    body.push(line);
  }

  throw new Error(`Could not find closing brace for interface ${interfaceName}`);
};

const normalizeGeneratedImports = (source: string) =>
  source.replaceAll('import("../../src/', 'import("./src/');

const formatInterfaceBody = (lines: ReadonlyArray<string>) =>
  normalizeGeneratedImports(
    lines.map((line) => `  ${line.replace(/^\t/, "")}`).join("\n")
  );

mkdirSync(join(projectRoot, ".cache"), { recursive: true });
const tempDir = mkdtempSync(join(projectRoot, ".cache", "wrangler-types-"));

try {
  const generatedSections = workerSpecs.map((spec) => {
    const rawPath = join(tempDir, `${spec.label.toLowerCase()}.d.ts`);

    run([
      "bunx",
      "wrangler",
      "types",
      "--config",
      spec.config,
      "--env-interface",
      spec.envInterface,
      rawPath
    ]);

    const raw = readFileSync(rawPath, "utf8");

    return {
      label: spec.label,
      env: formatInterfaceBody(extractInterfaceBody(raw, "Env")),
      stagingEnv: formatInterfaceBody(extractInterfaceBody(raw, "StagingEnv"))
    };
  });

  const runtimeRawPath = join(tempDir, "runtime.d.ts");
  run([
    "bunx",
    "wrangler",
    "types",
    "--config",
    "wrangler.toml",
    "--include-env",
    "false",
    runtimeRawPath
  ]);
  writeFileSync(
    runtimeOutputPath,
    normalizeGeneratedImports(readFileSync(runtimeRawPath, "utf8"))
  );

  const combinedOutput = [
    "/* eslint-disable */",
    "// Generated by `bun run cf:types`. Do not edit by hand.",
    `/// <reference path="./${runtimeOutputPath}" />`,
    "declare namespace WorkerConfiguration {",
    ...generatedSections.flatMap((section) => [
      `  interface ${section.label}StagingEnv {`,
      section.stagingEnv,
      "  }",
      "",
      `  interface ${section.label}Env {`,
      section.env,
      "  }",
      ""
    ]),
    "}"
  ].join("\n");

  writeFileSync(combinedOutputPath, combinedOutput);
} finally {
  rmSync(tempDir, { recursive: true, force: true });
}
