export const paperPatterns = [
  "https?://[^\\s<>\"]+\\.pdf(?:[?#][^\\s<>\"]*)?\\b",
  "https?://[^\\s<>\"]+/(?:download/pdf|fulltext)/\\d+(?:[?#][^\\s<>\"]*)?\\b",
  "arxiv\\.org/(?:abs|pdf)/\\d{4}\\.\\d{4,5}",
  "arxiv:\\d{4}\\.\\d{4,5}",
  "doi\\.org/10\\.\\d{4,}/",
  "(?:bio|med)rxiv\\.org/content/10\\.\\d{4,}/",
  "ncbi\\.nlm\\.nih\\.gov/pmc/articles/PMC\\d+",
  "nber\\.org/papers/w\\d+",
  "nber\\.org/system/files/working_papers/w\\d+/w\\d+\\.pdf",
  "papers\\.ssrn\\.com/sol3/papers\\.cfm\\?abstract_id=\\d+",
  "ssrn\\.com/abstract=\\d+",
  "proceedings\\.mlr\\.press/",
  "proceedings\\.icml\\.cc/",
  "proceedings\\.ijcai\\.org/",
  "eccv\\d{4}\\.org/papers/",
  "cvpr\\d{4}\\.thecvf\\.com/papers/",
  "science\\.org/doi/",
  "nature\\.com/articles/",
  "springer\\.com/article/",
  "sciencedirect\\.com/science/article/",
  "(?:www\\.)?sciencedirect\\.com/science/article/(?:pii/)?[A-Z0-9]+",
  "wiley\\.com/doi/",
  "tandfonline\\.com/doi/",
  "ieee\\.org/document/",
  "acm\\.org/doi/",
  "proquest\\.com/docview/",
  "ebscohost\\.com/products/research-databases/",
  "ingentaconnect\\.com/content/",
  "academia\\.edu/\\d+/",
  "philpapers\\.org/rec/",
  "hal\\.science/",
  "zenodo\\.org/record/\\d+",
  "figshare\\.com/articles/",
  "philsci-archive\\.pitt\\.edu/\\d+/?",
  "index\\.php/[a-zA-Z0-9_-]+/article/view/\\d+",
  "/article/view/\\d+/?",
  "research\\.?gate\\.net/",
  "academic\\.oup\\.com/",
  "aps\\.org/doi/",
  "acs\\.org/doi/",
  "ams\\.org/journals/",
  "asanet\\.org/research/",
  "aeaweb\\.org/articles",
  "psycharchives\\.org/",
  "eric\\.ed\\.gov/\\?id=",
  "semanticscholar\\.org/paper/",
  "arxiv\\.org/",
  "alphaxiv\\.org/",
  "chemrxiv\\.org/",
  "eartharxiv\\.org/",
  "psyarxiv\\.com/",
  "osf\\.io/preprints/",
  "econstor\\.eu/handle/",
  "socarxiv\\.org/",
  "engrxiv\\.org/",
  "sportrxiv\\.org/",
  "sociologicalscience\\.com/articles-v\\d+-\\d+-\\d+/?",
  "/articles-v\\d+/",
  "/volume/\\d+/article/\\d+/?",
  "plos\\w*\\.org/[^\\s<>\"]+",
  "mdpi\\.com/\\d+-\\d+/\\d+/\\d+",
  "frontiersin\\.org/articles/\\d+",
  "openreview\\.net/forum\\?id=",
  "jmlr\\.org/papers/",
  "aclweb\\.org/anthology/",
  "aclanthology\\.org/\\d{4}\\.[a-z]+-[a-z]+\\.\\d+/?",
  "aclanthology\\.org/[A-Z0-9.-]+/?",
  "journals\\.sagepub\\.com/",
  "dl\\.acm\\.org/doi/",
  "proceedings\\.neurips\\.cc/",
  "proceedings\\.mlr\\.press/",
  "oup\\.com/[^\\s<>\"]+/article/",
  "cambridge\\.org/core/journals/",
  "pubs\\.acs\\.org/doi/(?:abs|full|pdf)/10\\.\\d{4,}/",
  "pubs\\.acs\\.org/doi/10\\.\\d{4,}/",
  "acs\\.org/doi/(?:abs|full|pdf)/10\\.\\d{4,}/",
  "pubs\\.acs\\.org/journal/[a-z]+",
  "pubs\\.acs\\.org/toc/[a-z]+/\\d+/\\d+",
  "acs\\.org/content/acs/en/journals/",
  "pubs\\.acs\\.org/action/showCitFormats\\?doi=10\\.\\d{4,}/",
  "/doi/full/10\\.\\d{4,}/",
  "doi/10\\.\\d{4,}/",
  "doi:10\\.\\d{4,}/",
  "/doi/abs/10\\.\\d{4,}/",
  "/doi/pdf/10\\.\\d{4,}/",
  "/doi/(?:abs|pdf|full|epdf|pdfplus)/10\\.\\d{4,}/",
  "/doi/10\\.\\d{4,}/(?:full|pdf|abs|epub)/?",
  "/doi/book/10\\.\\d{4,}/",
  "/doi/chapter/10\\.\\d{4,}/",
  "/doi/proceedings/10\\.\\d{4,}/",
  "/doi/article/10\\.\\d{4,}/",
  "/doi/[a-z]+/10\\.\\d{4,}/",
  "annualreviews\\.org/(?:doi|content/journals)/10\\.\\d{4,}/",
  "annualreviews\\.org/journal/[a-z]+",
  "annualreviews\\.org/toc/[a-z]+/\\d+/\\d+",
  "(?:https?://)?(?:dx\\.)?doi\\.org/10\\.\\d{4,}/[a-zA-Z0-9._()/-]+",
  "doi:10\\.\\d{4,}/[a-zA-Z0-9._()/-]+",
  "jstor\\.org/stable/",
  "muse\\.jhu\\.edu/article/",
  "cairn\\.info/revue",
  "persee\\.fr/doc/",
  "erudit\\.org/en/journals/",
  "hprints\\.org/",
  "historycooperative\\.org/",
  "ahajournals\\.org/",
  "oxfordbibliographies\\.com/",
  "shakespearequarterly\\.org/",
  "linguisticsociety\\.org/",
  "anthropology-news\\.org/",
  "americananthro\\.org/",
  "ia\\.cr/\\d{4}/\\d{4}",
  "eprint\\.iacr\\.org/\\d{4}/\\d{4}",
  "pubmed\\.ncbi\\.nlm\\.nih\\.gov/\\d+/?",
  "ncbi\\.nlm\\.nih\\.gov/books/NBK\\d+/?",
  "ncbi\\.nlm\\.nih\\.gov/books/n/[a-zA-Z0-9]+/",
  "ncbi\\.nlm\\.nih\\.gov/pmc/articles/PMC\\d+/?",
  "ncbi\\.nlm\\.nih\\.gov/pubmed/\\d+/?",
  "ncbi\\.nlm\\.nih\\.gov/research/[a-zA-Z0-9-_]+/?",
  "heinonline\\.org/HOL/",
  "lawreview\\.org/",
  "jstor\\.org/stable/\\d+\\?.*law",
  "ssrn\\.com/sol3/papers\\.cfm\\?.*law",
  "nejm\\.org/doi/",
  "jamanetwork\\.com/journals/",
  "thelancet\\.com/journals/",
  "bmj\\.com/content/",
  "cochranelibrary\\.com/",
  "ahajournals\\.org/",
  "diabetesjournals\\.org/",
  "ascopubs\\.org/",
  "who\\.int/publications/",
  "cdc\\.gov/mmwr/",
  "repec\\.org/",
  "econpapers\\.repec\\.org/paper/",
  "econbiz\\.de/",
  "hbr\\.org/\\d{4}/",
  "mitsloan\\.mit\\.edu/publication/",
  "journals\\.sagepub\\.com/doi/.*management",
  "informs\\.org/Publications/",
  "aom\\.org/publications/",
  "aeaweb\\.org/articles\\?id=",
  "redalyc\\.org/",
  "cyberleninka\\.ru/article/",
  "J-STAGE\\.jst\\.go\\.jp/",
  "koreascience\\.or\\.kr/",
  "cnki\\.net/",
  "cscd\\.ac\\.cn/",
  "africajournals\\.org/",
  "ajol\\.info/",
  "sabinet\\.co\\.za/",
  "oxfordmusiconline\\.com/",
  "mtosmt\\.org/issues/",
  "artsjournal\\.com/",
  "tandfonline\\.com/.*culture",
  "arthistoryjournal\\.org/",
  "getty\\.edu/publications/",
  "journals\\.sagepub\\.com/home/msx",
  "film-philosophy\\.com/index\\.php/",
  "journals\\.sagepub\\.com/home/jte",
  "aera\\.net/publications/",
  "tandfonline\\.com/.*education",
  "ed\\.gov/pubsearch/",
  "eric\\.ed\\.gov/\\?id=",
  "lisr\\.org/",
  "ala\\.org/tools/publications/",
  "journals\\.ametsoc\\.org/",
  "agupubs\\.onlinelibrary\\.wiley\\.com/",
  "sciencedirect\\.com/.*environment",
  "int-res\\.com/",
  "esa\\.org/publications/",
  "agronomy\\.org/publications/",
  "crops\\.org/publications/",
  "soils\\.org/publications/",
  "forestry\\.org/publications/",
  "asme\\.org/publications/",
  "asce\\.org/publications/",
  "aiaa\\.org/publications/",
  "spe\\.org/en/publications/",
  "aiche\\.org/resources/publications/",
  "imeche\\.org/publications/",
  "istructe\\.org/publications/",
  "theiet\\.org/publishing/",
  "jsse\\.org/(?:issue|volume)/",
  "pmid:\\s?\\d{8}",
  "isbn:\\s?[\\d-]+"
];

export const contentPatterns = [
  "(?:excited|happy|pleased) to (?:share|announce|present)",
  "new (?:paper|preprint|work|research|study)",
  "our (?:paper|work|research|study|findings)",
  "(?:i|we) (?:just|recently) (?:published|uploaded|posted)",
  "(?:check out|take a look at) (?:our|my) (?:new |latest )?(?:paper|work|research)",
  "proud to share",
  "thread about (?:our|my)",
  "with (?:my )?(?:colleagues|collaborators|co-authors)",
  "joint work with",
  "led by",
  "(?:first|latest) author",
  "now (?:available|online|published|out)",
  "(?:preprint|paper) is (?:now |finally )?(?:up|live|out)",
  "accepted (?:at|to|in)",
  "to appear in",
  "forthcoming in",
  "\\u{1F4C4}|\\u{1F4DD}|\\u{1F4D1}|\\u{1F4F0}|\\u{1F52C}|\\u{1F9EA}|\\u{1F393}|\\u{1F4DA}",
  "paper (?:written|published|authored) by",
  "(?:arxiv|biorxiv|medrxiv)",
  "research (?:paper|article|study)",
  "journal of",
  "proceedings of",
  "conference on",
  "(?:published|accepted|appeared).*?\\(\\d{4}\\)|(?:\\(\\d{4}\\).*?(?:journal|conference|proceedings))",
  "et al\\.",
  "(?:journal|proceedings|transactions) of",
  "advances in",
  "review[s]? of",
  "annual (?:review|conference) on",
  "in press|in review|under review",
  "(?:paper|article) titled",
  "(?:published|presenting) (?:in|at) .{5,50}?(?:journal|conference|workshop)",
  "abstract[:;]",
  "(?:code|data|supplementary) (?:is )?available",
  "we (?:propose|present|introduce|demonstrate|show|describe)",
  "(?:paper|preprint) link",
  "(?:full|open) access",
  "(?:poster|talk|presentation) at",
  "(?:thesis|dissertation)",
  "full (?:text|paper|article)",
  "download (?:paper|article|pdf)"
];

export const pdfExclusions = new Set([
  "casetext.com",
  "congress.gov/",
  "courtlistener.com",
  "justia.com",
  "leagle.com",
  "pacer.gov",
  "senate.gov/",
  "supremecourt.gov",
  "uscourts.gov",
  "whitehouse.gov/"
]);

export const compiledPaperPatterns = paperPatterns.map(
  (pattern) => new RegExp(pattern, "iu")
);
export const compiledContentPatterns = contentPatterns.map(
  (pattern) => new RegExp(pattern, "iu")
);
